feature: ['feat/*', 'feature/*']
chore: ['chore/*']
bug: ['fix/*', 'bug/*']
build: ['build/*']
ci: ['ci/*']
docs: ['docs/*']
style: ['style/*']
refactor: ['refactor/*']
perf: ['perf/*']
test: ['test/*']
revert: ['revert/*']
