[package]
name = "ndisapi"
version = "0.1.0"
edition = "2021"
authors = ["Vadim Smirnov <vadim@ntkernel.com>"]
description = "NDIS API bindings for Rust"
license = "Apache-2.0"
documentation = "https://docs.rs/ndisapi"
repository = "https://github.com/firezone/ndisapi"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"

[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_System_IO",
    "Win32_Storage_FileSystem",
    "Win32_Networking_WinSock",
    "Win32_System_SystemInformation",
    ]

[dev-dependencies]
etherparse = "0.13"
clap = {version = "4.0.32", features = ["derive"]}
ctrlc = "3.2.4"
